# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(.*tests/.*|.*testing/.*|.*test.py$)'
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-toml
      #- id: check-json
      - id: check-yaml
        exclude: '(conda/meta.yaml|.pep8speaks.yml)'

  # use ffffff (black fork) for single quote normalization
  # (otherwise switch to black for double quotes)
  - repo: https://github.com/grktsh/ffffff
    rev: v2020.8.31
    hooks:
      - id: ffffff
        name: "Format code (ffffff)"
        exclude: '(^docs/.*|.*tests/.*|.*testing/.*|.*test.py$)'
        language_version: python3

#  - repo: "https://github.com/psf/black"
#    rev: "21.9b0"
#    hooks:
#      - id: "black"
#        language_version: python3
#        name: "Format code (black)"
#        exclude: '(^docs/.*|.*tests/.*|.*testing/.*|.*test.py$)'

  #- repo: "https://github.com/asottile/blacken-docs"
    #rev: "v1.11.0"
    #hooks:
      #- id: "blacken-docs"
        #name: "Format docs (blacken-docs)"
        #args: ["-l", "64"]
        #additional_dependencies:
          #- "black==21.9b0"

  #- repo: https://github.com/PyCQA/doc8
    #rev: 0.9.1
    #hooks:
      #- id: doc8
        #args:
          #- '--max-line-length=90'
          #- '--ignore=D001'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
        # exclude: ChangeLog\.rst$
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: '(^docs/.*|.*tests/.*|.*testing/.*|.*test.py$)'
        args:
          - --in-place
          - --remove-duplicate-keys
          - --remove-unused-variables

  #- repo: https://gitlab.com/pycqa/flake8
    #rev: 3.9.2
    #hooks:
      #- id: flake8
        #exclude: '(^docs/.*|.*tests/.*|.*testing/.*|.*test.py$)'
        #additional_dependencies: ["flake8-bugbear"]

  #- repo: https://github.com/PyCQA/bandit
    #rev: 1.7.0
    #hooks:
      #- id: bandit
        ##args: ["-ll", "-b", "bandit_baseline.json"]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        exclude: '(^docs/.*|.*tests/.*|.*testing/.*|.*test.py$)'
        args:
          [
            "-rn",
            "-sn",
            "--fail-under=4.00",
          ]

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

# re-running a pull request: you can trigger a re-run on a pull request by
#    commenting pre-commit.ci run (must appear on a line by itself).
# skipping push runs: skip a run by putting [skip ci], [ci skip],
#    [skip pre-commit.ci], or [pre-commit.ci skip] in the commit message.
